### ISSUE TITLE
Support distinct push and pull features

### ISSUE THREAD

**Issue by nickwynja** [elizagamedev/mujmap#26]
lieer and mbsync both have a nice feature where you can independently `push` local changes to the server as well as a `pull` remote changes, instead of doing a full sync.

What I often used and miss in mujmap is a workflow where I will do a full `sync`, then read, tag, and archive messages but then `push` up the changes to the server. `push` is usually a quicker operation and avoids any new messages getting pull down into my inbox until the next time that I `sync`. Yet I'm able to get the local changes pushed up to the server incase I later, for example, check my email on my phone.

**Comment by elizagamedev** [comment]
I agree, I intended to add this as a goal but forgot to make an issue for it.

**Comment by elizagamedev** [comment]
Fixed as of 1643034e565f6a16277199be76f3ff6c4d23bd02. I did not add `pull` as a distinct command for reasons semi-explained in the readme, but it's now possible to do a `push` without pulling.
