### ISSUE TITLE
Update documentation and sample config file for current Fastmail configuration

### ISSUE THREAD

**Issue by nigelm** [elizagamedev/mujmap#43]
See the information at [Updates to JMAP API and authentication](https://jmap.topicbox.com/groups/fastmail-api/Tc47db6ee4fbb5451/updates-to-jmap-api-and-authentication) on [Topicbox - Fastmail API](https://jmap.topicbox.com/groups/fastmail-api

In the config file, you need:-
```toml
session_url = "https://api.fastmail.com/.well-known/jmap"
```

The same document shows how to get an API key.

**Comment by robn** [comment]
#44. Good spot, thanks.
