### ISSUE TITLE
Timeouts not handled well

### ISSUE THREAD

**Issue by robn** [elizagamedev/mujmap#7]
I've been hacking on mujmap today on a very flaky network connection, which is leading to the program pretty regularly exiting with:

```
[2022-05-15T06:59:20Z DEBUG ureq::unit] response 200 to GET https://www.fastmailusercontent.com/publicjmap/download/ud0004100/G1c3c459181941951be1590e6fa0261b918a8919c/G1c3c459181941951be1590e6fa0261b918a8919c?type=text%2Fplain
[2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:33020, peer: 66.111.4.88:443, fd: 11 }
[2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:33022, peer: 66.111.4.88:443, fd: 14 }
[2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:54542, peer: 66.111.4.87:443, fd: 7 }
[2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:54534, peer: 66.111.4.87:443, fd: 8 }
error: Could not sync mail: Could not save email to cache: Could not create mail file `/home/robn/.cache/mujmap/!home!robn!mail!grue!cur!in_progress_download.4': timed out reading response
```

It continues from where it left off when restarted, so its mostly just an inconvenience.

I thought to catch timeouts and retry (much like `remote::get_reader` does) but I can't quite figure out where this error is actually coming from.

I'll have another run at it once I'm finished with with the current thing I'm doing, but maybe you will just say "oh, its just this" and flip a single bit and save me some time!

**Comment by elizagamedev** [comment]
I think I understand what's going on. The connection succeeds in remote.rs, but fails soon after during the actual copy operation from reader to writer in `download_into_cache`. I think the fix is probably just as simple as pulling up the retry logic out of remote.rs and around basically the entire body of the blob download `map` closure.

Thank you, I really appreciate the contributions 🙂

On Sun, May 15, 2022, at 12:08 AM, Rob N ★ wrote:
> 
> 
> I've been hacking on mujmap today on a very flaky network connection, which is leading to the program pretty regularly exiting with:
> 
> `[2022-05-15T06:59:20Z DEBUG ureq::unit] response 200 to GET https://www.fastmailusercontent.com/publicjmap/download/ud0004100/G1c3c459181941951be1590e6fa0261b918a8919c/G1c3c459181941951be1590e6fa0261b918a8919c?type=text%2Fplain
> [2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:33020, peer: 66.111.4.88:443, fd: 11 }
> [2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:33022, peer: 66.111.4.88:443, fd: 14 }
> [2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:54542, peer: 66.111.4.87:443, fd: 7 }
> [2022-05-15T06:59:20Z DEBUG ureq::stream] dropping stream: TcpStream { addr: 192.168.1.105:54534, peer: 66.111.4.87:443, fd: 8 }
> error: Could not sync mail: Could not save email to cache: Could not create mail file `/home/robn/.cache/mujmap/!home!robn!mail!grue!cur!in_progress_download.4': timed out reading response
`

**Comment by robn** [comment]
Nice! I've banged on it a little deliberately introducing some random latency and packet loss and it seems to be recovering ok. Good stuff, thanks!
